import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  @override
    Widget build(BuildContext context) {
        return Scaffold(
              appBar: AppBar(
                      backgroundColor: Color(0xFF003366),
                              title: Text('Tokenized Cards', style: TextStyle(fontFamily: 'Roboto')),
                                    ),
                                          body: Padding(
                                                  padding: const EdgeInsets.all(16.0),
                                                          child: Column(
                                                                    children: [
                                                                                Card(
                                                                                              elevation: 8,
                                                                                                            shape: RoundedRectangleBorder(
                                                                                                                            borderRadius: BorderRadius.circular(15),
                                                                                                                                          ),
                                                                                                                                                        child: ListTile(
                                                                                                                                                                        title: Text('Card 1 - Tokenized', style: TextStyle(fontFamily: 'Roboto')),
                                                                                                                                                                                        subtitle: Text('Card details here', style: TextStyle(fontFamily: 'Roboto')),
                                                                                                                                                                                                        leading: Icon(Icons.credit_card),
                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                              SizedBox(height: 10),
                                                                                                                                                                                                                                                          Card(
                                                                                                                                                                                                                                                                        elevation: 8,
                                                                                                                                                                                                                                                                                      shape: RoundedRectangleBorder(
                                                                                                                                                                                                                                                                                                      borderRadius: BorderRadius.circular(15),
                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                  child: ListTile(
                                                                                                                                                                                                                                                                                                                                                  title: Text('Card 2 - Tokenized', style: TextStyle(fontFamily: 'Roboto')),
                                                                                                                                                                                                                                                                                                                                                                  subtitle: Text('Card details here', style: TextStyle(fontFamily: 'Roboto')),
                                                                                                                                                                                                                                                                                                                                                                                  leading: Icon(Icons.credit_card),
                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                          bottomNavigationBar: BottomNavigationBar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: Color(0xFFF5F5F5),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          selectedItemColor: Color(0xFF003366),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  items: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            BottomNavigationBarItem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        icon: Icon(Icons.home),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    label: 'Home',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BottomNavigationBarItem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    icon: Icon(Icons.settings),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                label: 'Settings',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BottomNavigationBarItem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                icon: Icon(Icons.view_list),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            label: 'Tokens',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                BottomNavigationBarItem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            icon: Icon(Icons.info),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        label: 'About',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      