import 'package:flutter/material.dart';

class LoginScreen extends StatelessWidget {
  @override
    Widget build(BuildContext context) {
        return Scaffold(
              appBar: AppBar(
                      backgroundColor: Color(0xFF003366),
                              title: Text('Login', style: TextStyle(fontFamily: 'Roboto')),
                                    ),
                                          body: Padding(
                                                  padding: const EdgeInsets.all(16.0),
                                                          child: Column(
                                                                    crossAxisAlignment: CrossAxisAlignment.start,
                                                                              children: [
                                                                                          Text('Enter MPIN', style: TextStyle(fontSize: 18, fontFamily: 'Roboto')),
                                                                                                      SizedBox(height: 10),
                                                                                                                  TextField(
                                                                                                                                obscureText: true,
                                                                                                                                              decoration: InputDecoration(
                                                                                                                                                              hintText: 'MPIN',
                                                                                                                                                                              border: OutlineInputBorder(),
                                                                                                                                                                                              contentPadding: EdgeInsets.symmetric(horizontal: 16),
                                                                                                                                                                                                            ),
                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                    SizedBox(height: 20),
                                                                                                                                                                                                                                                ElevatedButton(
                                                                                                                                                                                                                                                              style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                                                              primary: Color(0xFF003366),
                                                                                                                                                                                                                                                                                              padding: EdgeInsets.symmetric(vertical: 12),
                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                          onPressed: () {
                                                                                                                                                                                                                                                                                                                                          // Navigate to Home Screen after login
                                                                                                                                                                                                                                                                                                                                                          Navigator.pushReplacementNamed(context, '/home');
                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                      child: Text('Login', style: TextStyle(fontFamily: 'Roboto')),
                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                              